### ISSUE TITLE
视频压缩问题

### ISSUE THREAD

**Issue by yolanda0628** [chenzhihui28/VideoRecorderAndCompressor#1]
demo运行不了啊, 可以把视频录制和视频压缩的步骤写详细点吗?  谢谢!!

**Comment by chenzhihui28** [comment]
运行不了？什么意思？工程报错了吗？
<img width="344" alt="qq20161114-0 2x" src="https://cloud.githubusercontent.com/assets/13568894/20250252/76e7bf76-aa47-11e6-86bc-164a5aa4d1e7.png">

**Comment by yolanda0628** [comment]
是的

**Comment by yolanda0628** [comment]
直接到项目报这个错

![image](https://cloud.githubusercontent.com/assets/6160834/20252043/98fb57aa-aa59-11e6-8569-61357855845c.png)

导module的话不报错,但是不能运行....

**Comment by chenzhihui28** [comment]
http://blog.csdn.net/u012964796/article/details/47000991
试试看？我这边删掉本地的重新从github clone也没发现有问题, 我这边是as 2.2，貌似这只是gradle配置的小问题
<img width="1385" alt="qq20161114-0 2x" src="https://cloud.githubusercontent.com/assets/13568894/20254749/36778e96-aa72-11e6-8688-0034ca41f39f.png">

**Comment by yolanda0628** [comment]
非常谢谢,可以运行了 ,还想请问一下,我把路径换成我手机上的图片的话  压缩失败   请问这是什么错 ? 
![image](https://cloud.githubusercontent.com/assets/6160834/20256327/bca1db42-aa7d-11e6-9b1f-c45e594aad32.png)

**Comment by chenzhihui28** [comment]
你给的路径是一个目录吧。。。
![image](https://cloud.githubusercontent.com/assets/13568894/20256480/da47ba26-aa7e-11e6-8329-a7707bc33be7.png)

**Comment by yolanda0628** [comment]
呀!  太 粗心了 ,,..
