### ISSUE TITLE
压缩失败

### ISSUE THREAD

**Issue by csh159** [chenzhihui28/VideoRecorderAndCompressor#10]
提示原因：CANNOT LINK EXEXUTABLE "/data/user/0/com.czh.testmpeg/files/ffmpeg":/data/data/com.czh.testmpeg/files/ffmpeg:has text relocations

**Comment by chenzhihui28** [comment]
targetSDKVersion设置的是多少？

**Comment by chenzhihui28** [comment]
有可能是project 中的配置 targetSdkVersion 大于so编译时使用的sdkversion导致的

**Comment by csh159** [comment]
targetSDKVersion 22 跟25试了也是会报错

**Comment by chenzhihui28** [comment]
貌似。。。7.0的机子会不行。。。我等空余的时候尽快解决，谢谢

**Comment by csh159** [comment]
好哦，谢谢！

**Comment by csh159** [comment]
这个提示是不是7.0以上读取不了这个文件？如果是这样我就加个

**Comment by csh159** [comment]
大哥兼容一下7.0咯，哈哈，是7.0运行不了！谢谢哈

**Comment by XingXingLeo** [comment]
特意买了个荣耀8青春版的来测试7.0，果然同样的问题，跪求兼容7.0啊！
另外，大哥，那个拍照能不能兼容横着拍啊？好吧，我知道我的要求有点多了……ffmpeg这东东太复杂

**Comment by chenzhihui28** [comment]
fixed
