### ISSUE TITLE
摄像头初始化失败。录制不了

### ISSUE THREAD

**Issue by wpsmgkn** [chenzhihui28/VideoRecorderAndCompressor#13]
摄像头初始化失败。录制不了，出现这个异常
java.io.FileNotFoundException: /storage/emulated/0/videoKit/1490001007171.mp4: open failed: EISDIR (Is a directory)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:409)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:128)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:117)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at android.media.MediaRecorder.prepare(MediaRecorder.java:691)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at com.czh.testmpeg.videorecord.CameraActivity.prepareMediaRecorder(CameraActivity.java:492)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at com.czh.testmpeg.videorecord.CameraActivity.access$1200(CameraActivity.java:63)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at com.czh.testmpeg.videorecord.CameraActivity$7.onClick(CameraActivity.java:406)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at android.view.View.performClick(View.java:4438)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at android.view.View$PerformClick.run(View.java:18422)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at android.os.Looper.loop(Looper.java:136)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5045)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at dalvik.system.NativeStart.main(Native Method)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err: Caused by: libcore.io.ErrnoException: open failed: EISDIR (Is a directory)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at libcore.io.Posix.open(Native Method)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
03-20 17:10:07.168 12542-12542/com.czh.testmpeg W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:393)

**Comment by DroidVent** [comment]
**Put these lines in manifest.xml**
 `<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />`
