### ISSUE TITLE
点击后显示摄像头初始化失败？

### ISSUE THREAD

**Issue by sdfasffsdf** [chenzhihui28/VideoRecorderAndCompressor#2]
点击后显示摄像头初始化失败？

**Comment by chenzhihui28** [comment]
报什么错？能看看日志吗

**Comment by chenzhihui28** [comment]
一开始请求的权限是否都给了？

**Comment by sdfasffsdf** [comment]
一开始弹窗显示需要权限，我的小米进入这个应该的权限内容，我都打勾了，返回后，点击录像的按钮，就吐司 摄像头初始化失败，程序返回了主界面，，所以很是奇怪？

**Comment by chenzhihui28** [comment]
日志呢

**Comment by sdfasffsdf** [comment]
今晚我回去看看哈，在上班，谢谢大神！

**Comment by sdfasffsdf** [comment]
W/System.err: java.io.FileNotFoundException: /mnt/sdcard/in.mp4: open failed: EACCES (Permission denied)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
W/System.err:     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
W/System.err:     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
W/System.err:     at android.media.MediaRecorder.prepare(MediaRecorder.java:758)
W/System.err:     at com.czh.testmpeg.videorecord.CameraActivity.prepareMediaRecorder(CameraActivity.java:490)
W/System.err:     at com.czh.testmpeg.videorecord.CameraActivity.access$1200(CameraActivity.java:62)
W/System.err:     at com.czh.testmpeg.videorecord.CameraActivity$7.onClick(CameraActivity.java:405)
W/System.err:     at android.view.View.performClick(View.java:4792)
W/System.err:     at android.view.View$PerformClick.run(View.java:19915)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:135)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5295)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)

手机存储的位置路径找不到，
因为不同相机，可能路径会出问题。
建议：较好的方法是通过Environment 来获取路径。

路径问题解决了，也可以录制了，但是压缩出来的视频是打不开的，时间关系，等调试完再跟大神讨论讨论。
