### ISSUE TITLE
请问这个压缩ffmpeg文件能不能变小点，因为直接影响打包apk，大10几兆

### ISSUE THREAD

**Issue by hytcyjb** [chenzhihui28/VideoRecorderAndCompressor#4]
请问一下，你的那个VideoRecorderAndCompressor 项目里面的录制完的视频通过ffmepg进行再次压缩可以让assets-->armeabi-v7a--->ffmpeg文件现在是14M，直接导致发布的apk变的很大，请问有方法让ffmpe文件变小（能够满足本地视频压缩即可），或者有什么其他的方法让apk打包的时候仅仅大一点点（大1M内）最多，者FFmpeg可以满足吗？如果不行，顺便问一下有其他方法吗？

**Comment by chenzhihui28** [comment]
那个是ffmpeg的库编译出来的。想要精简的话估计得你自己去下ffmpeg的库然后精简代码再编译出一个新的小一点的

**Comment by hytcyjb** [comment]
ffmpeg编译库的方法你那边有吗？方便发个看看不？

**Comment by chenzhihui28** [comment]
没有。。。。。
试试这个？http://blog.csdn.net/dgyanyong/article/details/12052857

**Comment by hytcyjb** [comment]
好的，我试试，谢啦

**Comment by baoti** [comment]
@chenzhihui28  这个项目中的 ffmpeg 是来自哪里呢？看了下 ffmpeg 版本是 3.3，并不是从 https://github.com/WritingMinds/ffmpeg-android 项目编译出来的。

**Comment by baoti** [comment]
我知道了，是来自 https://github.com/kesha-antonov/ffmpeg-android-java 这个项目。
