### ISSUE TITLE
ffmpeg有点大

### ISSUE THREAD

**Issue by qq245258365** [chenzhihui28/VideoRecorderAndCompressor#5]

**Comment by chenzhihui28** [comment]
不好意思最近比较忙碌没来得及看，这个工程参考的是https://github.com/WritingMinds/ffmpeg-android-java 的ffmpeg库，可能是因为作者将整个ffmpeg库都编译了的原因所以库有点大，而且不同的cpu架构也需要不同的二进制文件，所以加起来就显得更大了，或者你可以试试自己动手编译出ffmpeg的库，只需要视频的部分，应该会小一点，至于不同架构需要相应的二进制文件的话，这个只能够通过不同abi编译不同apk的方式来解决了。
