### ISSUE TITLE
视频压缩的时候如何让他停止

### ISSUE THREAD

**Issue by cat1024** [chenzhihui28/VideoRecorderAndCompressor#6]
压缩视频的时候如何让他停止下来，用户可能在压缩的时候退出当前页面，我需要让它停下来@chenzhihui28

**Comment by chenzhihui28** [comment]
已邮件回复，请查收
这个项目里面有一个jar包去完成ffmpeg的加载和最后命令的执行，这个jar包来源于http://writingminds.github.io/ffmpeg-android-java/ ，是一个ffmpeg的操作库，这里面的实现是一个asynctask来实现加载库和执行命令，你可以fork一下这个项目改一下向外提供一下停止执行的接口。至于问题2，压缩是用ffpmpeg，执行时间控制不了，但是可以控制的是录制视频的分辨率，我的这个工程里面也有，录制视频时可以选择录制的分辨率，还有就是改一下命令，也就是修改压缩的目标分辨率，目前貌似只有这两个方法了，压缩时间的确得看ffmpeg。
