### ISSUE TITLE
中途不能结束压缩进程

### ISSUE THREAD

**Issue by droidxiao** [chenzhihui28/VideoRecorderAndCompressor#8]
中途不能结束压缩进程

**Comment by chenzhihui28** [comment]
你好，这个项目里面有一个jar包去完成ffmpeg的加载和最后命令的执行，这个jar包来源于http://writingminds.github.io/ffmpeg-android-java/ ，是一个ffmpeg的操作库，这里面的实现是一个asynctask来实现加载库和执行命令，你可以fork一下这个项目改一下向外提供一下停止执行的接口。
